import type { Config } from 'tailwindcss';

const config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        qz: {
          gray100: '#FFFFFF',
          gray200: '#F6F7FB',
          gray300: '#EDEFF4',
          gray400: '#D9DDE8',
          gray500: '#939BB4',
          gray600: '#586380',
          gray700: '#2E3856',
          gray800: '#282E3E',
          gray900: '#1A1D28',
          twilight100: '#EDEFFF',
          twilight200: '#DBDFFF',
          twilight300: '#A8B1FF',
          twilight400: '#7583FF',
          twilight500: '#4255FF',
          twilight600: '#423ED8',
          twilight700: '#1F1C8B',
          twilight800: '#14125C',
          twilight900: '#0A092D',
          sunset100: '#FFF9E3',
          sunset200: '#FFEDAB',
          sunset300: '#FFDC62',
          sunset400: '#FFCD1F',
          sunset500: '#997700',
          mint100: '#E6FCF4',
          mint200: '#C7F7E6',
          mint300: '#98F1D1',
          mint400: '#59E8B5',
          mint500: '#18AE79',
          mint600: '#12815A',
          lilac100: '#FCF0FF',
          lilac200: '#F7D9FF',
          lilac300: '#EEAAFF',
          lilac400: '#E372FF',
          lilac500: '#9900BE',
          skyblue100: '#EAF9FF',
          skyblue200: '#CBF1FF',
          skyblue300: '#98E3FF',
          skyblue400: '#51CFFF',
          skyblue500: '#008EC4',
          lemon100: '#FDFFE9',
          lemon200: '#FAFFBB',
          lemon300: '#F5FF7D',
          lemon400: '#EBFF03',
          lemon500: '#D4E603',
          sherbert100: '#FFF6EF',
          sherbert200: '#FFE8D8',
          sherbert300: '#FFC38C',
          sherbert400: '#FF983A',
          sherbert500: '#D05700',
          cherry300: '#FF7873',
          cherry400: '#DA4543',
          cherry500: '#B00020',
          cucumber: '#D9FFCC',
          dandelion: '#ECE381',
          grape: '#A533FF',
          jam: '#D326D7',
          magenta: '#F442A0',
          navy: '#002C6D',
          paleIce: '#CCF9FF',
          periwinkle: '#A0C4FA',
          plum: '#5E0F5B',
          ruby: '#F6406C',
          rosewater: '#FDD2CA',
          seaGreen: '#009AA4',
          seaSpray: '#D3F0EB',
          scrim100: '#0A092D14',
          scrim300: '#0A092D80',
          shadow: '#282E3E14',
          none: '#00000000',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;

export default config;
